### ISSUE TITLE
Allow custom blocks to set color/state

### ISSUE THREAD

**Issue by marzzzello** [greshake/i3status-rust#1002]
Is it possible for a custom block to change colors?
I could not find anything so I assume this is not possible. But this would be a very nice feature.
I have a custom block and I want to set the state by my script so it shows the idle color if everything is ok and it should be possible to set the state to warning or critical so the color changes.

**Comment by ammgws** [comment]
Use JSON output:

```toml
[[block]]
block = "custom"
command = "echo '{\"icon\":\"weather_thunder\",\"state\":\"Critical\", \"text\": \"Danger!\"}'"
json = true
```
