### ISSUE TITLE
"inputs" not accepted for temperature block

### ISSUE THREAD

**Issue by Ploppz** [greshake/i3status-rust#1004]
According to the docs, it should be possible, but I get an error about deserialization, the field "inputs" not accepted.
I tried both i3status-rust from official Arch repos and i3status-rust-git from AUR.

**Comment by ammgws** [comment]
On an up-to-date Arch installation I copied the example config from the docs and it worked fine. What's your full config?

```toml
[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]
```
