### ISSUE TITLE
right click on disk space in order to update it immediately

### ISSUE THREAD

**Issue by Stunkymonkey** [greshake/i3status-rust#1015]
this is a feature request for the `block = "disk_space"`. I would like to have the latest value being displayed, when right clicking it.

**Comment by ammgws** [comment]
With https://github.com/greshake/i3status-rust/pull/1006 merged, the next step would be to also add support for other mouse buttons. Then if support for signals (https://github.com/greshake/i3status-rust/pull/822) is added for all blocks then you could set your command to send a signal to the block to update.

**Comment by ammgws** [comment]
Closing in favour of #1036. Keep on eye on that one!

**Comment by ammgws** [comment]
Async branch has now been merged into master (still some work to do before release is possible though), so I believe this should be possible by adding something like this to the end of your `disk_space` block config:

```toml
[[block.click]]
button = "right"
cmd = "kill -SIGUSR1 i3status-rs"
```

**Comment by MaxVerevkin** [comment]
> 

Or even better :)

```toml
[[block.click]]
button = "right"
update = true
```
