### ISSUE TITLE
It seems I can only have a single custom_dbus block

### ISSUE THREAD

**Issue by diegodorado** [greshake/i3status-rust#1024]
If I have this on my status.toml

```toml
[[block]]
block = "custom_dbus"
name = "DefaultSink"

[[block]]
block = "custom_dbus"
name = "DefaultSource"

```

when I query `qdbus i3.status.rs ` I only have the first subscribed listed
