### ISSUE TITLE
Random high CPU usage.

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1065]
After some time there appears to be a thread that maximizes CPU usage and it stays there even after I reload sway. I couldn't find out which block causes this because it happens quite rarely.

Did any one experienced this? The next time I'll have it I will attach a screenshot of `htop`.

Here is my config. Running on latest master commit, but this also happened to me about a week ago.

```toml
theme = "slick"

[icons]
name = "awesome5"
[icons.overrides]
music = "  "

[[block]]
block = "github"
hide_if_total_is_zero = true

[[block]]
block = "net"
device = "wlp3s0"
clickable = true
format = "{signal_strength} {graph_down} {speed_down} {speed_up}"
format_alt = "{ssid}"
interval = 2

[[block]]
block = "cpu"
interval = 1
info = 40
format = "{barchart} {utilization}"

[[block]]
block = "memory"
format_mem = "{Mup}%"
clickable = false

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{average}°"
chip = "*-isa-*"

[[block]]
block = "sound"

[[block]]
block = "music"
max_width = 15
buttons = ["play"]

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "{layout}"

[[block]]
block = "time"
interval = 60
format = "%d/%m %R"
```
