### ISSUE TITLE
discussion: add formatting parameters for format key specifiers

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1108]
Issues regarding spacing come up often - most recently ones like these: #1107, #1051, #1049 regarding number padding.

For these "padding" issues, I propose we expand on the initial work done in #750 by also adding syntax for setting the padding/number format for format specifiers.

Memory block example where the ":04" would zero-pad the number.
```toml
[[block]]
block = "memory"
format_swap = "{Mug:02}"
```

Sound block example where the ": >2" would pad the number with spaces.
```toml
[[block]]
block = "sound"
format = "{volume: >2}"
```
