### ISSUE TITLE
Discussion: Move pre-compiled themes and icon sets to `/usr/share/i3status-rust`

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1109]
With #1106 merged, this config is now correct:
```toml
[icons]
file = "material-nf"
[theme]
file = "slick"
```
given that `/usr/share/i3status-rust/themes/slick.toml` and `/usr/share/i3status-rust/icons/material-fn.toml` exist.

So my idea is that instead of having hard-coded icon sets and themes, we can provide them in `.toml` files. This makes `themes.rs` and `icons.rs` cleaner by splitting data and the actual code.

Any thoughts?
