### ISSUE TITLE
Partial brightness icons reversed

### ISSUE THREAD

**Issue by GladOSkar** [greshake/i3status-rust#1125]
I've noticed something weird with my `backlight` icon:

![brightness](https://user-images.githubusercontent.com/9497832/111869838-7912e500-8981-11eb-8782-a7000d20e0fb.gif)
(alt-text: Scrolling from 5-100% Brightness: Starts at dark icon, then goes from bright to dark, then ends on bright again)

I use this to reverse the direction in my config and it usually worked fine:
```toml
[icons.overrides]
backlight_empty = " 🌑 "
backlight_partial1 = " 🌘 "
backlight_partial2 = " 🌗 "
backlight_partial3 = " 🌖 "
backlight_full = " 🌕 "
```

If i remove that section, the order is entirely reversed (so correct for non-color emoji).

I am aware of the new `invert_icons` option and it works fine, i just wanted to draw attention to the fact that something was changed that shuffled these icons around for some people. So a `wontfix` is acceptable if this is okay as a breaking change.
