### ISSUE TITLE
Disable icons on blocks

### ISSUE THREAD

**Issue by ram02z** [greshake/i3status-rust#1133]
Some blocks like the time block I would prefer to have without an icon prepending it. My previous workaround was to override the icon with an empty string, however, upon updating to the latest commit, this workaround doesn't work properly any more (see below). Is there another way to disable icons? Blocks like the memory block have a config option to disable the icon, I would very much like this be in the default config.

<meta http-equiv="content-type" content="text/html; charset=utf-8"><img src="https://i.imgur.com/fbFQfQw.png">

> sway version v1.5
> i3status-rs 0.20.0 (commit ef2e881 2021-03-23)

**Comment by MaxVerevkin** [comment]
This should work
```toml
[[block]]
icons_format = " "
block = "time"
interval = 30
format = "%d/%m %R"
```
