### ISSUE TITLE
system load block formatting

### ISSUE THREAD

**Issue by PicoJr** [greshake/i3status-rust#1144]
Hello,

commit: c4cb70b

"Load" block formatting appears slightly buggy `"m"` character should not be displayed.

```
❯ ./target/debug/i3status-rs status.toml
{"version": 1, "click_events": true}
[
[{"full_text":" LOAD 1min avg: 190m ","name":"0","instance":"0","markup":"pango"}],
[{"full_text":" LOAD 1min avg: 170m ","name":"0","instance":"0","markup":"pango"}],
[{"full_text":" LOAD 1min avg: 170m ","name":"0","instance":"0","markup":"pango"}],
^C
```

with `status.toml`:

```toml
[[block]]
block = "load"
format = "1min avg: {1m}"
interval = 1
```

> Probably linked to #1112
