### ISSUE TITLE
Backlight icon missing

### ISSUE THREAD

**Issue by GladOSkar** [greshake/i3status-rust#1146]
Hi!

After updating to the latest `master` (with the new theme files), where previously i had a beautiful color moon emoji to show my brightness, it now shows this `i4` text:

![image](https://user-images.githubusercontent.com/9497832/113201655-0c91c300-926a-11eb-9aa5-4f532fdccf12.png)

I only use
```
[icons]
name = "awesome"

[[block]]
block = "backlight"
invert_icons = true
root_scaling = 2
```

Any ideas?

**Comment by MaxVerevkin** [comment]
Weird. It works for me...

**Comment by GladOSkar** [comment]
Huh.

Accrding to the `TOML` spec, 5-character (5 nibble) codepoints aren't allowed. They must be:
```
\uXXXX     - unicode         (U+XXXX)
\UXXXXXXXX - unicode         (U+XXXXXXXX)
```

I checked and
```
backlight_empty = "\U0001F315"
backlight_full  = "\U0001F311"
```

works, while

```
backlight_empty = "\u1F315"
backlight_full  = "\u1F311"
```
soes not

**Comment by ammgws** [comment]
Did you manage to get any further info on this? 
(Works for one person but not the other)

**Comment by GladOSkar** [comment]
Not me, i'm stumped as to why it works for @MaxVerevkin. How is it on your system?

**Comment by ammgws** [comment]
Can you reproduce using another block or a Custom block? That way I can quickly check it out as well.

**Comment by MaxVerevkin** [comment]
Well, it's really weird, since we all use the same parser. @ammgws I suppose it works for you too, right?

**Comment by ammgws** [comment]
Actually with this:

```toml
[icons]
name = "awesome5"
[icons.overrides]
time = "\u1F315"

[[block]]
block = "time"
```

I get:

> >./target/debug/i3status-rs test1146.toml
> {"version": 1, "click_events": true}
> [
> [{"full_text":"|","color":"#a9a9a9","background":"#000000","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":" ἱ5 Tue 06/04 23:24 ","color":"#93a1a1","background":"#000000","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],

icon is being displayed as "i5". I guess that means I reproduced it?

**Comment by GladOSkar** [comment]
> Can you reproduce using another block or a Custom block? That way I can quickly check it out as well.

Sure, try something like
```toml
[[block]]
block = "custom"
command = "echo '{\"icon\":\"backlight_full\",\"text\":\"Test\"}'"
json = true
```

**Comment by GladOSkar** [comment]
> I guess that means I reproduced it?

Yeah i guess but the question is rather whether it works in the theme file, right?

**Comment by ammgws** [comment]
And confirmed that this works as per GladOSkar's post:

```toml
[icons]
name = "awesome5"
[icons.overrides]
time = "\U0001F315"
```

However if the U is lowercase then it just dispalyed "F315" :laughing:
