### ISSUE TITLE
Error with custom block json with no icon

### ISSUE THREAD

**Issue by nolanl** [greshake/i3status-rust#1156]
```
Internal error in context 'get_icon()': icon '' not found: please check your icon file or open a new issue on GitHub if you use a precompiled icons.
```

icons = "awesome"

The json I emitted was:
```
{"state":"Critical", "text":" Reboot Required"}
```

**Comment by GladOSkar** [comment]
@MaxVerevkin #1135 or rather addf871 introduced this regression by removing the `"" => ""` icon mapping. Since that probably isn't really possible with the new icon file toml syntax, we should probably special-case it either in the icon retrieval or in the custom block.

**Comment by MaxVerevkin** [comment]
I think it's better to handle this in the `custom` block.

**Comment by GladOSkar** [comment]
I also noticed that i can't get custom json to work at all with the latest git version, i always get

```
Error parsing JSON: expected value at line 1 column 1
```

even with the example from `blocks.md`. Is that just me?

**Comment by MaxVerevkin** [comment]
I tried 
```toml
[[block]]
block = "custom"
command = "echo '{\"icon\":\"weather_thunder\",\"state\":\"Critical\", \"text\": \"Danger!\"}'"
json = true
```
And it works. @GladOSkar which example did you try?
