### ISSUE TITLE
Failed using memory block with any formatting

### ISSUE THREAD

**Issue by gbaranski** [greshake/i3status-rust#1198]
Hello, that's how my config looks like
```toml
theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
```
And it does not want to work for me, here is what I see on stdout:
```
{"version": 1, "click_events": true}
[[{"background":"#000000","color":"#dc322f","full_text":" Internal error in context 'util': Unknown placeholder in format string: {mem_used} ","name":"0","separator":false,"separator_block_width":0}]


Internal error in context 'util': Unknown placeholder in format string: {mem_used}
```

And the same thing happens no matter which formatting I use.

OS: NixOS Unstable
Version: 0.14.7
