### ISSUE TITLE
`material-nf`: `net` block is printed in reverse order when loopback device is used

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1206]
Output in the terminal seems OK.

## Config

```toml
icons = "material-nf"

[[block]]
block = "net"
format = "{signal_strength} {graph_down}{speed_down;K}{speed_up;K}"
interval = 1
```

## Video

https://user-images.githubusercontent.com/34583604/116897308-c9968700-ac3d-11eb-946d-ec0465214474.mp4
