### ISSUE TITLE
pacman block prevents use

### ISSUE THREAD

**Issue by poldi1405** [greshake/i3status-rust#1214]
```toml
[[block]]
block = "pacman"
interval = 300
format_up_to_date = "0"
critical_updates_regex = "(linux|linux-lts|linux-zen|linux-ck|firefox|sudo|librewolf|linux-amd|firefox)"
```
causes invalid i3bar-json because the output of the pacman DB update is not piped away. Causing output similar to this:
```json
{"version": 1, "click_events": true}
:: Paketdatenbanken werden synchronisiert …
Fehler: failed to synchronize all databases (Kann Datenbank nicht sperren)
[[{"background":null,"color":"#424242","full_text…
```

If I read the source correct then it should put the database in `/tmp`, since it is tmpfs potential issues should be resolved after a restart, but they are not.
