### ISSUE TITLE
music block: need to pango escape icons when using no icon set

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1219]
Sway log
>00:00:10.328 [common/pango.c:64] pango_parse_markup ' < ' -> error Error on line 1 char 11: “ ” is not a valid character following a “<” character; it may not begin an element name

Test config
```toml
[[block]]
block = "music"
buttons = ["prev", "play", "next"]
marquee_interval = 10
marquee_speed = 0.25
dynamic_width = true
separator = " "
on_click = "~/.local/bin/i3-quickterm mpsyt"
on_collapsed_click = "~/.local/bin/i3-quickterm mpsyt" 
interface_name_exclude = ["firefox"]
```
