### ISSUE TITLE
How to hide units in memory block?

### ISSUE THREAD

**Issue by msrd0** [greshake/i3status-rust#1228]
I used to have the following configuration:

```toml
[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}/{MTg} GB"
format_swap = "{SUg}/{STg} GB"
```

This displayed, for example, `1.8/32 GB`, displaying the unit only once, which is the perfect balance between readability and space usage. After the update, I tried the replacement

```toml
[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G}/{mem_total;G} GB"
format_swap = "{swap_used;G}/{swap_total;G} GB"
```

However, this renders `1.8GB/ 31GB GB`. Even if I removed the manual unit from the format string, this still shows the unit twice, which is unneccessary and wastes space. Also, there is a random space after the slash that I didn't ask for.

How can I configure i3status-rust to show the memory string it used to show?
