### ISSUE TITLE
pacman block erroneously reports no package updates available

### ISSUE THREAD

**Issue by Noah-Kennedy** [greshake/i3status-rust#1239]
Package updates have not been displaying since the last update. My status bar is always reporting that everything is up-to-date. In my case, it is displaying the format string "updated", even when there are package updates available. I have confirmed via `i3status-rs --version` that I am on version `0.20.1`.

`journalctl` is showing the following error every time it checks for updates:
```
/usr/bin/fakeroot: line 175: pacman -Sy --dbpath "/tmp/checkup-db-noah" --logfile /dev/null: No such file or directory
```
Here is my pacman block:
```toml
[[block]]
block = "pacman"
interval = 600
format = "{pacman} + {aur} = {both}"
format_singular = "{pacman} + {aur} = {both}"
format_up_to_date = "updated"
critical_updates_regex = "(linux | nvidia | amd-ucode | linux-firmware | openssl)"
aur_command = "paru -Qua"
```

This applies both to the AUR and to the pacman repos.
