### ISSUE TITLE
block: temperature: introduced spacing before digit

### ISSUE THREAD

**Issue by ivankovnatsky** [greshake/i3status-rust#1303]
I think this commit: https://github.com/greshake/i3status-rust/commit/12ce5846a574cce534c7a2aadef048f4330019d9 introduced that.

![image](https://user-images.githubusercontent.com/75213/132374275-cdf7a9e5-45d5-40fa-b486-e685b089b01a.png)

while i looked over the code, still could not understand what caused this (i'm not great at rust, sorry).

already moved to sysfs driver:

```toml

[[block]]
block = "temperature"
chip = "coretemp"
collapsed = false
driver = "sysfs"
inputs = ["Package id 0"]

```

**Comment by GladOSkar** [comment]
Pretty sure this is also #1231

**Comment by GladOSkar** [comment]
Pretty sure this is also #1231 and was added with the new formatting system.

Have a look there so see the right way to do it

@MaxVerevkin seems to me like the new behavior might not be a very good default, we might want to have a look at that

**Comment by MaxVerevkin** [comment]
I have a few ideas:

- We can just change the default "min-width" to 1, however those who relied on defaults might get confused.
- We can also add "refer to (...) for more info" in the blocks' docs. And perhaps formatting docs can be rewritten in a more clear way?
- (not an actual option) Maybe not provide the default value for "min-width" at all?

**Comment by ivankovnatsky** [comment]
ah, got it,

```toml
[[block]]
block = "temperature"
chip = "coretemp"
collapsed = false
driver = "sysfs"
inputs = ["Package id 0"]

[block.format]
full = "{max:2^3}"
short = ""
```

this looks good to me.

i spotted this only on temperature widget.
