### ISSUE TITLE
Battery block: always highlighted with bg color even on 100%/Full

### ISSUE THREAD

**Issue by ivankovnatsky** [greshake/i3status-rust#1317]
battery block always shows a bg color highlight even on full charge, I presume the widget still thinks it's a good state not idle yet.

i3status version: 0.20.4
theme: space-villain
 
i3status-rust config:

```toml
...

[[block]]
allow_missing = true
block = "battery"
hide_missing = true

...

[icons]
name = "material-nf"

...

[theme]
name = "space-villain"

[theme.overrides]
separator = ""
```

![image](https://user-images.githubusercontent.com/75213/137266970-530dfd63-5478-4030-bdb5-2f5d47f73a8f.png)

```console
cat /sys/class/power_supply/*/status --plain
Full
acpi
Battery 0: Full, 100%
```

i did fixed it for myself defining a good state bg color as idle one.

```toml
[[block]]
allow_missing = true
block = "battery"
hide_missing = true

[block.theme_overrides]
good_bg = "#06060f"
```
