### ISSUE TITLE
Unable to use font awesome icons

### ISSUE THREAD

**Issue by ayushnix** [greshake/i3status-rust#1347]
I'm not sure if I'm missing something but I'm not able to get Font Awesome 5 icons to work with i3status-rust. I'm trying to change the icons used by the `toggle` block but I keep getting

```
Internal error in context 'get_icon()': icon '...' not found in your icons file. If you recently upgraded to v0.2 please check NEWS.md
```

`NEWS.md` says that if `/usr/share/i3status-rust/awesome5.toml` is present, it should get picked up automatically. That file is present. I've tried using other icons but I keep this error again and again. I also went ahead and created `~/.config/i3status-rust/icons/awesome5.toml` but that didn't help either.

```
$ i3status-rs --version
i3status-rs 0.20.5

$ grep 'font pango' .config/sway/config
font pango:SF Mono, Font Awesome 5 Free, Font Awesome 5 Brands, 16

$ fc-list | grep -i awesome
/usr/share/fonts/OTF/Font Awesome 5 Brands-Regular-400.otf: Font Awesome 5 Brands,Font Awesome 5 Brands Regular:style=Regular
/usr/share/fonts/OTF/Font Awesome 5 Free-Regular-400.otf: Font Awesome 5 Free,Font Awesome 5 Free Regular:style=Regular
/usr/share/fonts/OTF/Font Awesome 5 Free-Solid-900.otf: Font Awesome 5 Free,Font Awesome 5 Free Solid:style=Solid

$ cat .config/i3status-rust/config.toml
theme = "native"
icons = "awesome5"

[[block]]
block = "toggle"
command_state = "systemctl --user show --property=ActiveState wlsunset | grep '=active'"
command_on = "systemctl --user start wlsunset"
command_off = "systemctl --user stop wlsunset"
icon_on = "\uf093"
icon_off = "\uf019"

$ ll /usr/share/i3status-rust/icons/
.rw-r--r-- 3.5k root root  7 Nov 00:34 awesome.toml
.rw-r--r-- 2.5k root root  7 Nov 00:34 awesome5.toml
.rw-r--r-- 4.6k root root  7 Nov 00:34 material-nf.toml
.rw-r--r-- 2.7k root root  7 Nov 00:34 material.toml

$ ll .config/i3status-rust/icons/
.rw-r----- 2.5k user user 13 Nov 02:41 awesome5.toml

$ grep 'uf093' /usr/share/i3status-rust/icons/awesome5.toml
net_up = "\uf093"
$ grep 'f019' /usr/share/i3status-rust/icons/awesome5.toml
net_down = "\uf019"
```

Am I doing something wrong?

**Comment by GladOSkar** [comment]
Are the icons also not working in the regular block configuration or is it just your custom `toggle`?

And in the error line you mention, does it actually say the icon `...` was not found or does it say which one?

**Comment by GladOSkar** [comment]
Oh and looking at the docs/source, you config should be:

```
icon_on = "net_up"
icon_off = "net_down"
```
instead of the literal codepoints.
```

**Comment by ayushnix** [comment]
> Are the icons also not working in the regular block configuration or is it just your custom `toggle`?

I've only tested this on the `toggle` block for now and it doesn't seem to work. All the other blocks seem to be working fine.

> And in the error line you mention, does it actually say the icon `...` was not found or does it say which one?
> Oh and looking at the docs/source, you config should be:
> `icon_on = "net_up"`
> `icon_off = "net_down"`
> instead of the literal codepoints.

It shows the specific icon I entered and says that it wasn't found. So, let's say I write

```
icon_on = "thermometer_full"
icon_off = "thermometer_empty"
```

in this case, it just writes `icon 'thermometer_full' not found ...`. If I use literal codepoints,

```
icon_on = "\uf2c7"
icon_off = "\uf2cb"
```

it shows `icon '<the actual icon>' not found ...`

The icons are taken from [this](https://fontawesome.com/v5.15/icons/thermometer-empty?style=solid) and [this](https://fontawesome.com/v5.15/icons/thermometer-full?style=solid)

**Comment by MaxVerevkin** [comment]
> ```
> $ ll /usr/share/i3status-rust/icons/
> .rw-r--r-- 3.5k root root  7 Nov 00:34 awesome.toml
> .rw-r--r-- 2.5k root root  7 Nov 00:34 awesome5.toml
> .rw-r--r-- 4.6k root root  7 Nov 00:34 material-nf.toml
> .rw-r--r-- 2.7k root root  7 Nov 00:34 material.toml
> 
> $ ll .config/i3status-rust/icons/
> .rw-r----- 2.5k user user 13 Nov 02:41 awesome5.toml
> ```

Did you just copy the file?

> ```
> icon_on = "thermometer_full"
> icon_off = "thermometer_empty"
> ```

There are no such icons in the provided files. I would recommend adding them with [overriding](https://github.com/greshake/i3status-rust/blob/master/doc/themes.md#overriding-themes-and-icon-sets)

**Comment by GladOSkar** [comment]
If the default configuration is finding the correct icons, but your overrides aren't, that really can only be because either you're either using icon names that don't exist in the loaded icon files or you mistyped them (maybe some invisible spaces or similar?)

Using the icon literals (`\u....`) in the config options should not work.

**Comment by ayushnix** [comment]
I was able to get the icons working but do I need to add and maintain the list of icons I want to use in a `~/.config/i3status-rust/icons/awesome5.toml`? Do I need to keep that file in sync with the upstream `awesome5.toml` or can I simply mention the extra icons I'm using?

**Comment by MaxVerevkin** [comment]
>  do I need to add and maintain the list of icons I want to use in a ~/.config/i3status-rust/icons/awesome5.toml if they're not present in the default awesome5.toml file?

No.

> can I simply mention the extra icons I'm using?

If you are referring to overriding then yes.

**Comment by ayushnix** [comment]
> No.

How do I use custom icons then? If I mention `icon_on = thermometer_full` in the toggle block, it doesn't work, even though I have mentioned `icons = awesome5` in the beginning of the config file. I don't want to override an existing icon in [this](https://github.com/greshake/i3status-rust/blob/master/doc/themes.md#available-icon-overrides) list.

**Comment by MaxVerevkin** [comment]
> How do I use custom icons then?

Does this work?

```toml
[icons]
name = "awesome5"
[icons.overrides]
my_toggle_on = "\uf093"
my_toggle_off = "\uf019"

[[block]]
block = "toggle"
command_state = "systemctl --user show --property=ActiveState wlsunset | grep '=active'"
command_on = "systemctl --user start wlsunset"
command_off = "systemctl --user stop wlsunset"
icon_on = "my_toggle_on"
icon_off = "my_toggle_off"
```

---

But on the other note, I think it would make sense to implement `[block.icons_overrides]` in addition to `[block.theme_overrides]`:


```toml
icons = "awesome5"

[[block]]
block = "toggle"
command_state = "systemctl --user show --property=ActiveState wlsunset | grep '=active'"
command_on = "systemctl --user start wlsunset"
command_off = "systemctl --user stop wlsunset"
[block.icons_overrides]
toggle_on = "\uf093"
toggle_off = "\uf019"
```
