### ISSUE TITLE
Add manpage generation to GitHub actions?

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1422]
Keep forgetting to update them since it's manual process ATM

**Comment by MaxVerevkin** [comment]
Something like this should work:

```yaml
name: Generate Man Pages
on:
  release:
    types: [published]
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: generate manpages
        run: |
          man/generate.sh
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add man
          git commit -m "Generate Man Pages"
          git push origin master

```
