### ISSUE TITLE
v0.30: battery block regression when device is missing (UPower)

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1495]
When device is not available the block errors, but it should just be hidden since `hide_missing = true`:

![image](https://user-images.githubusercontent.com/20397027/174491031-fdc7052f-98b4-477a-aabf-71dee25241e3.png)

```toml
[[block]]
block = "battery"
driver = "upower"
device = "battery_ps_controller_battery_d0obcoc1oe6o57o5c"
format = "PS5: $percentage|PS5: N/A"
full_format = "PS5: $percentage"
hide_missing = true
[block.theme_overrides]
alternating_tint_bg = "#FFFFFFFF"
alternating_tint_fg = "#FFFFFFFF"
# TODO: change to confirm menu
[[block.click]]
button = "left"
cmd = "allow_only_one_instance sway_setup_tv_gaming"
```
