### ISSUE TITLE
v0.30: temperature block fails on click with default config

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1496]
```toml
[[block]]
block = "temperature"
```
![recording](https://user-images.githubusercontent.com/20397027/174491718-fe4f73c5-2c47-411d-8f7b-fa07baf4406b.gif)
