### ISSUE TITLE
v0.30: music block fails to render if no media playing

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1497]
https://user-images.githubusercontent.com/20397027/174586327-6c7ca83a-fc87-408f-af2d-568b07af45ba.mp4

```toml
[[block]]
block = "music"
format = "$combo.rot-str(20) $prev $play $next "
[[block.click]]
button = "left"
cmd = "allow_only_one_instance sonixd"
```

**Comment by MaxVerevkin** [comment]
Can you please post the full error message?

**Comment by MaxVerevkin** [comment]
And your `format` config.

**Comment by ammgws** [comment]
![image](https://user-images.githubusercontent.com/20397027/174744062-d84883be-4c0c-42ae-9e91-17ed2ee25caa.png)

```toml
[[block]]
block = "music"
format = "$combo.rot-str(20) $prev $play $next "
[[block.click]]
button = "left"
cmd = "allow_only_one_instance sonixd"
```

Pretty sure I tried with the default config too, and also adding `|` to the placeholders. I haven't had time to properly inspect the new codebase so am just upping these as I go, so sorry if the fix is trivial.
