### ISSUE TITLE
sound: handle both pipewire and pulseaudio device names when mapping

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1525]
Pulseaudio sep char is a colon `_`, where as in Pipewire it is an underscore `:`.
Thus when using `[block.mappings]` on a system where you might switch between the two backends from time to time, you need to specify two different mappings for the same device:

```toml
[[block]]
block = "sound"
driver = "pulseaudio"
[block.mappings]
# pulseaudio
"alsa_output.pci-0000_00_1b.0.analog-stereo" = "headphones"
# pipewire-pulse
"alsa_output.pci-0000:00:1b.0.analog-stereo" = "headphones"
```

Instead we could just replace all colons with underscores in output_name here so either way works:

https://github.com/greshake/i3status-rust/blob/2aca056dafe58693009d353ecbdd010291803dbf/src/blocks/sound.rs#L158-L163
