### ISSUE TITLE
v0.30: change load default format to match v0.22

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1526]
```toml
[[block]]
block = "load"
```

v0.22:
"full_text":" LOAD 2.2 "

v0.30:
"full_text":" 1 " (missing decimal part)
