### ISSUE TITLE
Allow theme overrides to link to existing colors

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1527]
For example in `kdeconnect` block could then do:

```toml
[[block]]
block = "kdeconnect"
format = "$bat_charge $connected{OK}|^phone_disconnected"
```
Where `phone_disconnected` is an icon from the icon file, and `^` is just example syntax for specifying icons

**Comment by ammgws** [comment]
This could be useful for themes as well, not just icons.

Instead of this:

```toml
[[block]]
block = "sound"
driver = "pulseaudio"
device = "@DEFAULT_SOURCE@"
[block.theme_overrides]
# switch idle and warning around in order to get warning when mic is *not* muted
idle_bg = "#f44336"
idle_fg = "#000000"
warning_bg = "#424242"
warning_fg = "#ffffff"
```

This would be much better (again note that the syntax is for illustrative purposes - still need to find about the best way to implement):
```toml
[[block]]
block = "sound"
driver = "pulseaudio"
device = "@DEFAULT_SOURCE@"
[block.theme_overrides]
# switch idle and warning around in order to get warning when mic is *not* muted
idle_bg = "#{warning_bg}"
idle_fg = "#{warning_fg}"
warning_bg = "#{idle_bg}"
warning_fg = "#{idle_fg}"
```

**Comment by MaxVerevkin** [comment]
> This could be useful for themes as well, not just icons.

I actually had a PoC that did this at some point, but I decided not to include it because there were a lot of decisions to be made. But if this is a desirable feature (I think it is), we can discuss it here.

**Comment by ammgws** [comment]
Is that code still around in a commit somewhere?

**Comment by MaxVerevkin** [comment]
> Is that code still around in a commit somewhere?

No, but it wasn't too complicated.

**Comment by MaxVerevkin** [comment]
Perhaps something like this?

```toml
idle_bg = { link = "warning_bg" }
idle_fg = { link = "warning_fg" }
warning_bg = { link = "idle_bg" }
warning_fg = { link = "idle_fg" }
```
