### ISSUE TITLE
Battery: add more examples to the docs

### ISSUE THREAD

**Issue by tsymalla** [greshake/i3status-rust#1545]
Previously (in a build from around mid of May), my i3status-rust setup was showing the battery leftover time via {time} correctly. However, now in v0.30, with $time it does not show anything anymore, and it takes a bit of time to display the percentage initially.

```
[[block]]
block = "battery"
format = "$percentage|N/A $time"
device = "DisplayDevice"
driver = "upower"
```

**Comment by MaxVerevkin** [comment]
This should work:

```toml
[[block]]
block = "battery"
format = "$percentage $time|N/A"
device = "DisplayDevice"
driver = "upower"
```

The problem was that `$time` was _after_ `|`. This means that format was split into two parts: `$percentage` and `N/A $time`. The second one displays only when the first one fails.
