### ISSUE TITLE
custom block with click doesn't work

### ISSUE THREAD

**Issue by TornaxO7** [greshake/i3status-rust#1551]
If I add the following to my config:
```toml
[[block]]
block = "custom"
cycle = ["echo ON", "echo OFF"]
interval = 1
[[block.click]]
button = "left"
cmd = "<command>"
```
then I'm getting the error that the field `click` doesn't exist.
