### ISSUE TITLE
v0.22.0 - Spotify icon (from FA6) is very small compared to other icons

### ISSUE THREAD

**Issue by welcoMattic** [greshake/i3status-rust#1553]
![image](https://user-images.githubusercontent.com/773875/177118034-8d57f1a1-6a11-42e3-8421-6fdeb53c10fc.png)

The image speaks itself, I have no idea why suddenly the spotify icon has been reduced.

If you need me to post something like my config, or logs, tell me

**Comment by MaxVerevkin** [comment]
See #1477

**Comment by welcoMattic** [comment]
It's not all icons, it's just spotify.

Here is my config:

```toml
theme = "dracula.toml"
scrolling = "natural"

[icons]
name = "awesome6"

[icons.overrides]
music_next = "\uf051"
music_prev = "\uf048"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]
on_collapsed_click = "spotify"
on_click = "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpri>
hide_when_empty = false
marquee_interval = 5
marquee_speed = 0.3
dynamic_width = true
max_width = 120
format = "{combo} "
[block.theme_overrides]
info_bg = "#50fa7b"
idle_bg = "#282A36"
idle_fg = "#F8F8F2"
[block.icons_overrides]
music = "\uf1bc"
```

And the trick in https://github.com/greshake/i3status-rust/issues/1477 doesn't work well, it shifts the music label to the bottom.

![image](https://user-images.githubusercontent.com/773875/177410279-34e2188d-6917-4139-b582-476cfbdcadd0.png)
