### ISSUE TITLE
Unknown Placeholder in format string

### ISSUE THREAD

**Issue by bemeurer** [greshake/i3status-rust#156]
When trying to run i3status-rust with a weather block configured as such
```toml
[[block]]
block = "weather"
#format = "{weather} ({location}) {temp}°, {wind} m/s"
service = { name = "openweathermap", api_key = "XXX", city_id = "5392952", units = "metric" }
```
I get the following error
```
thread 'main' panicked at 'Unknown placeholder in format string: {weather}', /checkout/src/libcore/option.rs:874:4
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: __libc_start_main
  17: <unknown>
```
