### ISSUE TITLE
No interfaces shown in NetworkManager block if VPN connected and primary_only=true

### ISSUE THREAD

**Issue by learnitall** [greshake/i3status-rust#1575]
Hey folks,

I've noticed what I think is a bug during my day-to-day usage of the project. I'm on `v0.21.10`, installed through [home-manager](https://github.com/nix-community/home-manager) on NixOS. Essentially, if I enable `primary_only` and then connect to a VPN, the NetworkManager block goes blank.\:

```json
{"full_text":"","color":"#859900FF","background":"#FDF6E3FF","separator":false,"separator_block_width":0,"markup":"pango"}
```
If it would help to take screenshots or provide more output, please let me know. I believe this is related to https://github.com/greshake/i3status-rust/issues/1016, which lead to a PR which causes VPN connections to be skipped over while rendering the block.

If this isn't a real bug and my config is just bad, let me know. Otherwise, I'm up for getting a PR in the works to address this.

Here's my config: 

```toml
[[block]]
ap_format = "{ssid} ({strength})"
block = "networkmanager"
device_format = "{icon}{name} {ap}"
primary_only = true
```

Thanks!
