### ISSUE TITLE
Remove top-level `icons` and `theme`

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1578]
I'd rather just have one way to do it, since right now you can either do:

```toml
theme = "solarized-dark"
icons = "awesome"
```

or 

```toml
[theme]
name = "solarized-dark"
[icons]
name = "awesome"
```

but you end up needing to do it the latter anyway if you ever put any top-level theme or icon overrides in your config.

We only ended up like this in order to keep compat with configs when overrides were first added, but with 0.3 I think it's a good time to cut off some of the cruft. It would also make our documentation much simpler.

**Comment by MaxVerevkin** [comment]
Also I think it'd be a good idea to merge `name` and `file`. Perhaps into `theme`/`icons`. This might seem redundant, but we already have this with `[block] block = "..."`.

```toml
[theme]
theme = "solarized-dark"
[icons]
icons = "awesome"
```
