### ISSUE TITLE
Can't use multiple custom_dbus blocks when they're in different bars

### ISSUE THREAD

**Issue by RobinRamael** [greshake/i3status-rust#1579]
Thanks you so much for the work on the async branch. I've been waiting to use multiple dbus blocks for a while :)  I've been testing master to see if I can already do what I'd like.

I have two status bars, top and bottom. When I have multiple dbus blocks in the same bar, everything works fine, but when I move one of them to the other bar, none or only one of the bars will work.

Smallest config to reproduce this with:

`config-top.toml`:
```toml
[[block]]
block = "custom_dbus"
path = "/Foo"
```

`config-bottom.toml`:
```toml
[[block]]
block = "custom_dbus"
path = "/Baz"
```

I'm guessing this has something to do with two different instances of the process fighting over who gets the dbus namespace. An easy fix would be to have a namespace for each bar, although that's not very clean. Another idea could be to make the namespace a setting you can override per block? I'm no expert on dbus itself, so maybe there's another way.

cheers
