### ISSUE TITLE
weather: add `autolocate_interval` option.

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1594]
Calling `find_ip_location()` on each update might not bee needed in many cases.

```toml
autolocate_interval = 3600 # Every hour
autolocate_interval = "once" # Call find_ip_location() only once
```
