### ISSUE TITLE
net block: No SSID and signal strength for wifi device

### ISSUE THREAD

**Issue by sebastianst** [greshake/i3status-rust#1607]
* Version: `0.22.0`
* Kernel: `5.19.4-arch1-1`
* Block configuration:
```toml
[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid} {signal_strength} {speed_down;K}"
interval = 5
```
* `nmcli dev wifi list` shows SSID and strength
* `iw` is installed and
  * `iw dev wlp2s0 info` shows info, but no SSID
  * `iw dev wlp2s0 link` shows the SSID

The net block with the above configuration doesn't show the SSID or signal strength. The down speed is shown, however. I use a very similar setup and config on other laptops and it works there. Just installed it on a new laptop, where it doesn't work. Any ideas?
