### ISSUE TITLE
net: handle missing wifi more gracefully

### ISSUE THREAD

**Issue by matthiaskrgr** [greshake/i3status-rust#1608]
I initially noticed that the net block would sometimes just show "failed to render text"  / "frequency not found".When I refreshed, the error would usually go away.
A week later I noticed that this would usually happen right after suspending so I dug a bit deeper and found that just disconnecting from a wifi would basically "break" the block and 
````
hide_missing = true
hide_inactive = true
````
doesn't fix it unfortunately :/

It would be nice if the wifi block could just "minimize" or hide itself while not connected to a wifi (I think this actually was the case a couple months ago..?)

my config:

````toml
[[block]]
block = "net"
device = "wlp4s0"
format = "$signal_strength $speed_down $graph_down $speed_up $graph_up $frequency $ssid"
#ssid = true
#ip = true
#graph_down = true
hide_missing = true
hide_inactive = true

[[block]]
block = "net"
device = "enp0s31f6"
format = " $speed_down $graph_down $speed_up $graph_up"
#ip = true
#graph_down = true
````
