### ISSUE TITLE
music: play/next/prev via click cmd instead of button

### ISSUE THREAD

**Issue by marzzzello** [greshake/i3status-rust#1610]
I don't think it's currently possible to do this:
Play/Pause the music player by clicking anywhere in the music player instead of just the small button.
I've tried to use `cmd = "playerctl play-pause"` but it will often use some random player in the background and not the one that is displayed in the status bar. Is there a better solution without using buttons?

Something like this would be nice:

```toml
[[block]]
block = "music"
[[block.click]]
button = "left"
block_cmd = "play"
```

Or is there a DBus event from the music block that I can use in a script?
