### ISSUE TITLE
custom: v0.30.0 hide_when_empty doesn't work when json "text" is empty

### ISSUE THREAD

**Issue by marzzzello** [greshake/i3status-rust#1611]
The block should be hidden for the following command output and config (according to docs):

```json
{
  "state": "Idle",
  "icon": "memory_swap",
  "text": ""
}
```

```toml
[[block]]
block = "custom"
command = "~/path/to/script.py"
hide_when_empty = true
interval = 1
json = true
```

When the output is `{}` or icon and text are empty strings, the block is hidden but not when only the text is an empty string.
In the doc it says
>hide_when_empty: Hides the block when the command output (**or json text field**) is empty

In v0.22.0 it worked like described in the docs. If this new behavior is wanted then the docs should be fixed.
