### ISSUE TITLE
sound block question setup

### ISSUE THREAD

**Issue by scippio** [greshake/i3status-rust#1623]
Hi,
I can setup one volume control for my first sink and one for another? I have two sinks:
```
	name: <alsa_output.pci-0000_00_1f.3.analog-stereo>
	name: <bluez_sink.FC_58_FA_00_BB_8A.a2dp_sink>
```
I'm tried add something like this into first block:
```
device = "bluez_sink.FC_58_FA_00_BB_8A.a2dp_sink"
```
and this into second:
```
device = "alsa_output.pci-0000_00_1f.3.analog-stereo"
```

but still control only bluetooth speaker...

:( thanks for help

version: 0.22.0

**Comment by MaxVerevkin** [comment]
Can you try replacing `device = ` with `name = `? I have a similar setup and this works for me:

```toml
[[block]]
block = "sound"
name = "alsa_output.pci-0000_03_00.6.HiFi__hw_Generic_1__sink"

[[block]]
block = "sound"
name = "bluez_output.00_18_09_92_1B_BA.a2dp-sink"
```
