### ISSUE TITLE
∑ character on format

### ISSUE THREAD

**Issue by Tecnologer** [greshake/i3status-rust#1633]
There is a summation character on the blocks where I guess there is a missing block item, but I've checked the documentation, even the code, but I cannot figure out what I'm doing wrong. If you can guide me through  I'll appreciate it, thank you in advance.

![image](https://user-images.githubusercontent.com/8458967/193480883-ba760de2-9e6e-4553-9c80-67f04ce4f47a.png)

My version: `i3status-rs 0.30.0 (commit 51fd9e5d 2022-10-02)`

Here is my status.toml file:

```toml
[theme]
theme = "solarized-dark"

[icons]
icons = "awesome5"

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart.str() $utilization.eng() "
format_alt = " $icon $frequency.eng(){ $boost.str()|} "

[[block]]
block = "battery"
interval = 30
good = 60
warning = 30
critical = 15
format = " $icon $percentage "
full_format = " $icon $percentage "
empty_format = " $icon $percentage "


[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
alert_unit = "GB"
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(2) "

[[block]]
block = "memory"
display_type = "memory"
format_mem = " $icon $mem_total_used_percents.eng(2) "
format_swap = " $icon $swap_used_percents.eng(2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " %a %d/%m %R "
```
