### ISSUE TITLE
Announcements: Breaking changes

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1641]

**Comment by MaxVerevkin** [comment]
#1640

**temperature**: `collapsed` option is removed and now you can use `format_alt = " $icon "` to maintain the behavior

**Comment by MaxVerevkin** [comment]
#1644

**memory**: `clickable`, `display_type`, `format_mem` and `format_swap` are removed and now you can use `format` and `format_alt` to maintain the behavior

**Comment by MaxVerevkin** [comment]
#1686

- `pass` has been removed form click handler config options.
- `apt` `dnf` `pacman`: Clicking on the block does not cause an update by default anymore. To replicate that behavior use
  ```toml
  [[block.click]]
  # Updates the block on left click
  button = "left"
  update = true
  ```
- `rofication`: Clicking on the block does not open `rofication-gui` by default anymore. To replicate that behavior use
  ```toml
  [[block.click]]
  button = "left"
  cmd = "rofication-gui"
  ```

**Comment by MaxVerevkin** [comment]
#1698

- Instead of positional arguments, format templates now use named arguments, i.e. `$speed_down.eng(w:3,p:K,hide_unit:true)` instead of `$speed_down.eng(3,_B,K)`. See documentation [here](https://greshake.github.io/i3status-rust/i3status_rs/formatting/index.html).
- `rot-str` formatter has been removed. To replicate its behavior, use `rot_interval` argument of `str`. For example `$ssid.str(max_w:10, rot_interval:0.2)`.

**Comment by MaxVerevkin** [comment]
#1713 replaces `cpu` icon with`cpu_low`, `cpu_med` and `cpu_high`. Don't forget to run `./install.sh`. If you were overriding `cpu` icon, you now have to override these three icons instead.

**Comment by MaxVerevkin** [comment]
#1718 

- **music**: `seek_step` was replaced with `seek_step_secs`.

**Comment by MaxVerevkin** [comment]
#1723 changes **time** block formatting and removes `locale` option.

### Before

```toml
[[block]]
block = "time"
locale = "fr_BE"
format = " $icon %d/%m %R "
```

### After

```toml
[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:fr_BE) "
```
