### ISSUE TITLE
memory: rename `format_mem` and `format_swap` to `fromat` and `format_alt`

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1642]
About the memory block: `format_mem` and `format_swap` already behave as `format` and `format_alt`. So you can have

```toml
[[block]]
block = "memory"
format_mem = " ^icon_memory_mem $mem_used_percents.eng(1) "
format_swap = " ^icon_memory_mem $mem_used / $mem_total "
```

What we can do is just rename `format_mem` -> `format` and `format_swap` -> `format_alt` and drop `clickable`. But then either we should have two `$icon` placeholders (e.g. `$icon_mem` and `$icon_swap`) or just drop `$icon` and let users use the `^icon_` syntax.

_Originally posted by @MaxVerevkin in https://github.com/greshake/i3status-rust/issues/1635#issuecomment-1277118973_
