### ISSUE TITLE
How to add idle inhibitor in i3status-rs

### ISSUE THREAD

**Issue by kpzhao** [greshake/i3status-rust#1647]
Hi, Many I ask you how to add idle inhibitor like waybar in i3status-rust?
thanks in advance

**Comment by MaxVerevkin** [comment]
Idle inhibitor block is not implemented in `i3status-rs`.

From a quick look at `waybar`'s implementation, it seems that they communicate with wayland compositor directly via `idle_inhibit_unstable_v1` protocol. This might be problematic to implement in `i3status-rs` because
- Currently we don't communicate with wayland directly
- (From my understanding) the `idle_inhibit_unstable_v1` protocol requires a visible surface to be created

**Comment by rachitve6h2g** [comment]
Is there any way for it? It'd be a huge help if it could. Because I see that waybar handles the swayidle systemd user service pretty well. And with something like uwsm, to handle it using a toggle script doesn't seem very good. The [script](https://gist.github.com/noncomplete/2f0e60e9a84540927fd4a76f311e9922) that I use doesn't interact that way. This script does inhibit the idle service but as soon as I click on the toggle button again, the screen goes black and i have to enter my passswd again, despite being active at the time of doing it.

**Comment by bim9262** [comment]
I don't have swayidle set up, but check to see if this works (in an interactive python shell, closing the shell will release the inhibit). Make sure python-dbus is installed.

```python
import dbus
session_bus = dbus.SessionBus()
object = dbus.SystemBus().get_object("org.freedesktop.login1", "/org/freedesktop/login1")
interface = dbus.Interface(object, "org.freedesktop.login1.Manager")
fd = interface.Inhibit("sleep", "test", "test", "block").take()
```

If running that script blocks swayidle from sleeping then we can do the equivalent in a native block.

You should see the block listed when you run `systemd-inhibit --list`

**Comment by ammgws** [comment]
@rachitve6h2g Can you simply  just start/stop the swayidle systemd user service via the block? It is what I have used for a long time without experiencing any issues:

```toml
[[block]]
block = "toggle"
command_on = "systemctl --user start swayidle"
command_off = "systemctl --user stop swayidle"
command_state = "systemctl --user status swayidle &>/dev/null; test $status -eq 0; and echo on"
# shouldnt this be default? possible bug from PR1618
format = " $icon "
interval = 10
[block.icons_overrides]
toggle_on = ""
toggle_off = ""
```

If it still causes your screen to timeout when toggling it back on, maybe it has to do with your swayidle config?

This is mine:
```
timeout 300 'echo Timeout 300s: lock screen && chayang && loginctl lock-session'
timeout 600 'swaymsg --quiet "output * power off" && echo Timeout 600s: power off' resume 'swaymsg --quiet "output * power on" && echo Resume: power on'
```
