### ISSUE TITLE
music block is hidden despite not setting `hide_when_empty`

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1657]
Most likely due to #1618

**Comment by MaxVerevkin** [comment]
Can you share your config?

**Comment by ammgws** [comment]
```toml
[[block]]
block = "music"
if_command = '[[ "$(</etc/hostname)" == *"desk"* ]]'
format = " $icon $combo.rot-str(20) $prev $play $next|"
interface_name_exclude = [".*kdeconnect.*"]
[[block.click]]
button = "middle"
cmd = "allow_only_one_instance sonixd --enable-features=UseOzonePlatform --ozone-platform=wayland"
```
No players open:
```sh
>busctl --user list | rg MediaPlayer2
org.mpris.MediaPlayer2.playerctld                                      - -               -        (activatable) -                 -       -
```

Player open:
```sh
>busctl --user list | rg MediaPlayer2
org.mpris.MediaPlayer2.Sonixd                                     826826 electron        ammgws :1.618        session-1.scope   1       -
org.mpris.MediaPlayer2.playerctld                                      - -               -        (activatable) -                 -       -
```

Haven't had time to debug but pretty sure it shouldnt be hitting the `api.hide()` code if `hide_when_empty` isn't set.
