### ISSUE TITLE
v0.30: Screenshot example does not work.

### ISSUE THREAD

**Issue by ZackMitkin** [greshake/i3status-rust#1689]
My setup:
1. Installed with `yay -S i3status-rust-git`, which uses version `i3status-rust-git-0.30.0.r2848.gf2642f03-1`
2. I coppied the examples/screenshot.sh and modified it to just be this:
    ```bash
    # ~/screenshot.sh
    
    # open screenshot tool
    scrot -s -q 100 -o ~/Pictures/screenshot.png
    # copy to clipboard
    xclip -sel clip -t image/png -i ~/Pictures/screenshot.png
    ```
    Running `sh ~/screenshot.sh` from terminal works as expected. I can select the portion of screen I want to capture and it's saved to clipboard.

3. I have this block set in `~/.config/i3status-rust`
    ```toml
    [[block]]
    block = "custom"
    command = "echo ' \uf030 '" # assumes fontawesome icons
    interval = "once"
    shell = "bash"
    [[block.click]]
    button = "left"
    cmd = "sh ~/screenshot.sh"
    ```

    and it shows up fine:
    ![image](https://user-images.githubusercontent.com/20427502/209820732-79427845-b2b6-4f81-a8c6-a1a4868a4458.png)

But, on click it does nothing. I couldn't find a way to see any logs with this or debug further. 

A couple things I have tried is to just put `touch ~/test` in the screenshot script, clicking on the icon does create the empty `test`. 
I've also tried to just put the scrot command directly into the `cmd = "..."` section, which also doesn't work.

I'm wondering if there's any other way to debug why `scrot` isn't running? Any help will be greaty appreciated!

**Comment by MaxVerevkin** [comment]
I don't use X11, so the only idea I have is to capture the output of that script and see if there are any errors:

```toml
[[block]]
block = "custom"
command = "echo ' \uf030 '" # assumes fontawesome icons
interval = "once"
shell = "bash"
[[block.click]]
button = "left"
cmd = "sh ~/screenshot.sh 2>/tmp/custom_block.log"
```
