### ISSUE TITLE
docker block doesn´t show podman containers

### ISSUE THREAD

**Issue by rochacbruno** [greshake/i3status-rust#1701]
Hi,

I know this block is specifically for docker, however I decided to open the issue anyway.

I am using https://github.com/greshake/i3status-rust/blob/v0.22.0/doc/blocks.md#docker 
```toml
[[block]]
block = "docker"
interval = 2
format = "{running}/{total}/{images}"
```

And I have switched from docker-compose to podman-compose and AFAIK podman doesn't talk to docker socket. So if I check `docker ps` it shows 0 running containers, while `podman ps` shows my compose containers.

So I leave some open questions.

- Should docker block support podman?
- Should a new block `podman` be added?
- Should users customize by their own using a `custom` block?

Thanks
