### ISSUE TITLE
feature: service status via dbus integration

### ISSUE THREAD

**Issue by leongross** [greshake/i3status-rust#1712]
On devices using `systemd`: To continuously check if a service is running (i.e. `tor.service`) one could use `dbus` to query for the status of a certain service.
There already exists a project interfacing the [dbus in Rust](https://github.com/diwic/dbus-rs).

Currently a working solution without dbus could look like this, which should be replaced with propper dbus querying.

```toml
[[block]]
block = "custom"
command = "systemctl status tor 1&>/dev/null && echo TOR|| echo -"
```
