### ISSUE TITLE
ZFS ARC not included in $mem_avail since 0.30.0

### ISSUE THREAD

**Issue by HorayNarea** [greshake/i3status-rust#1744]
I have 16GB total memory, about 8GB are currently in use by ARC:
![grafik](https://user-images.githubusercontent.com/1871153/220484009-b38c95df-ae81-43fb-a8e0-999c31e1bf6f.png)

but

```toml
[[block]]
block = "memory"
format = " Total: $mem_total - Total Used: $mem_total_used - Used: $mem_used - Buffers: $buffers - Cache: $cached - Free: $mem_free - Avail: $mem_avail "
```

shows only 1GB available, even though it correctly identified ARC as cache (= easily freeable when memory is needed):

>Total: 16GB - Total Used: 15GB - Used:  6GB - Buffers: 131KB - Cache:  8GB - Free: 1GB - Avail:  1GB

I'm not fluent in Rust, but to me it looks like before this release you manually calculated `mem_avail` (including the ARC as available):
https://github.com/greshake/i3status-rust/blob/refs/tags/v0.22.0/src/blocks/memory.rs#L179-L185

and now `mem_avail` is directly read from `/proc/meminfo`, which does not account for ARC?
https://github.com/greshake/i3status-rust/blob/v0.30.0/src/blocks/memory.rs#L231-L263

On the other hand, `htop` shows about ~50% available memory:
![grafik](https://user-images.githubusercontent.com/1871153/220483501-48cc6550-e17b-4002-af18-83c485dbb9e1.png)

I'm not entirely sure which of these 2 methods is the correct way to handle ARC (leaning towards "just like `htop` does / 0.22.x did it") but both tools handling it differently is kinda confusing.
