### ISSUE TITLE
time block does not respect locale since 0.30.0

### ISSUE THREAD

**Issue by HorayNarea** [greshake/i3status-rust#1746]
```toml
[[block]]
block = "time"
format = "$timestamp.datetime(format:'%A, %Y-%m-%d %H:%M:%S', locale:de_DE)"
```

even though `locale:de_DE` is set I still get:
> Wednesday, 2023-02-22 03:18:21

where I would expect

> Mittwoch, 2023-02-22 03:18:21
