### ISSUE TITLE
Failed to render text error for volume block

### ISSUE THREAD

**Issue by maximyurevich** [greshake/i3status-rust#1795]
Failed to render text for volume block when I press mute button. Version 0.30.3
```toml
[[block]]
block = "sound"
max_vol = 100
driver = "auto"
format = " $icon $volume "
[block.icons_overrides]
volume_muted = " 婢"
volume = "奔"
```
