### ISSUE TITLE
block custom format

### ISSUE THREAD

**Issue by ayoubelmhamdi** [greshake/i3status-rust#1800]
```toml
[[block]]
block = "custom"
command = "get_bandwith"
interval = 1
```
```c
  // ...
  unsigned long diff_packet = update_tx_packets(tx_packets) / 1024;
  char s[5];
  snprintf(s, sizeof(s), "%4lu", diff_packet);
  printf("%4s kb\n", s);
```
I am currently padding my numbers with blank spaces when they are less than 4 characters long. However, the output appears to be trimmed by i3status-rs. I would prefer to avoid having the blocks in my status bar move around when the status is updated.

**Comment by GladOSkar** [comment]
https://github.com/greshake/i3status-rust/blob/master/src/blocks/custom.rs#L242

True, we do trim the normal output. As a workaround, you can use JSON mode though:

```toml
[[block]]
block = "custom"
json = true
command = "get_bandwith"
interval = 1
```

```C
  // ...
  printf("{\"text\":\"%4s kb\"}\n", s);
```

Since this trimming was like this for a long time i don't know if it makes sense to change it now since it's basically expected behavior, but @MaxVerevkin might have some better insight. Maybe it's only done to get rid of newlines?

**Comment by ayoubelmhamdi** [comment]
think's for your help.
I think the better way to handle trimming is to make a `custom` block support some format like:
```toml
[[block]]
block = "custom"
command = "get_bandwith"
command = "{custom:4}"
```
that's easy to understand and more exepected

**Comment by GladOSkar** [comment]
That's also not a bad idea imo

**Comment by MaxVerevkin** [comment]
> Maybe it's only done to get rid of newlines?

Probably. And it's been there since at least v0.10 :)

Also how about extending the json protocol like this?

```json
{
    "vals": [
        "bandwith": 1234
    ]
}
```

```toml
[[block]]
block = "custom"
command = "get_bandwith"
format = " $bandwith.eng(w:4) "
```
