### ISSUE TITLE
Custom block - cycle commands

### ISSUE THREAD

**Issue by piec** [greshake/i3status-rust#1814]
Hi All,

I'm upgrading to v0.30 and I either do not understand the custom block cycle mechanism:

I took the following block in the following comment so it should be correct: https://github.com/greshake/i3status-rust/issues/1705#issuecomment-1399315971

```toml
[[block]]
block = "custom"
shell = "sh"
cycle = ["echo '🐑'", "cat /etc/hostname"]
[[block.click]]
button = "left"
cmd = "<command>"
```

When clicking on the block the following is executed on my system: `/usr/bin/sh -c <command>`.
The `<command>` string is not replaced by the actual command.
Am I using it correctly? is it a bug?

Thanks,
Pierre

Tested versions: v0.30.4, bbcb42d42671642f0e6ddfab0dc737ab9606fb20

**Comment by MaxVerevkin** [comment]
I am not sure what `cmd = <command>` was supposed to do in the original comment, but if you just want to cycle between "🐑" and the hostname when you click on the block, you don't need it:

```toml
[[block]]
block = "custom"
shell = "sh"
cycle = ["echo '🐑'", "cat /etc/hostname"]
```

If you want to also execute something on each click while still cycling:

```toml
[[block.click]]
button = "left"
cmd = "notify-send hi"
action = "cycle"
```

You can also remap the cycling action to any button you want.
