### ISSUE TITLE
Allow for specifying custom padding character

### ISSUE THREAD

**Issue by ptrcnull** [greshake/i3status-rust#1820]
Currently, when using the `eng` formatter and specifying width 1 greater than actual number width, the number gets [padded with a space][1], which looks weird for some numbers:

```toml
[[block]]
block = "cpu"
format = " c$utilization.eng(width:2) "

[[block]]
block = "memory"
format = " m$mem_used_percents.eng(width:2) "
```

![image](https://user-images.githubusercontent.com/26630168/224125584-1632b44c-a169-45c8-8f29-3d61dd62c18f.png)

[1]: https://github.com/greshake/i3status-rust/blob/0f1322b165d91092366df11a5d3a9972f8f26d58/src/formatting/formatter.rs#L368
