### ISSUE TITLE
bluetooth: add info/good/warning/critical options

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1830]
My bluetooth headset has three battery states: 100%, 70% and 20% (I don't know why). Currently 100 and 70 are both considered "good".

We can either add config options similar to what battery block has, or try something like:

```toml
[[block]]
block = "bluetooth"
mac = "..."
[block.battery_states]
"0..=20" = "critical"
"21..=70" = "warning"
"71..=100" = "good"
```

Personally I find info/good/warning/critical options not very intuitive, but please share your opinions.
