### ISSUE TITLE
cpu: can't show decimal cases with `$frequency`

### ISSUE THREAD

**Issue by thiagokokada** [greshake/i3status-rust#1832]
Up till release `0.22.0` when I had:

```toml
[[block]]
block = "cpu"
format = "{frequency}"
```

This was the result:
![2023-03-15_20-43-11-screenshot](https://user-images.githubusercontent.com/844343/225620380-cef2e5a8-372d-44cf-8dc1-83df91df1e1d.png)

I can see the decimal cases in the frequency block, so `2.7GHz` in the screenshot case.

With release `0.30.5`, with:

```TOML
[[block]]
block = "cpu"
format = " $icon $frequency "
```

This is what I get instead:
![2023-03-16_12-36-46-screenshot](https://user-images.githubusercontent.com/844343/225620398-9613731f-36b2-4fc2-a23a-b01ac27ecb9d.png)

Also tried:

```TOML
[[block]]
block = "cpu"
format = " $icon $frequency.eng(prefix:M) "
```

Same result.

At least looking at the [formatting documentation](https://greshake.github.io/i3status-rust/i3status_rs/formatting/index.html), there is no obvious way to increase the precision either.

**Comment by thiagokokada** [comment]
Oh I see, this works:

```
[[block]]
block = "cpu"
format = " $icon $frequency.eng(prefix:M,w:3) "
```

It wasn't obvious to me but the whole issue is that `2.` would already be two characters, and this is why it wasn't appearing. You need to set `w:3` to allow `2.4GHz` for example.

**Comment by moghwan** [comment]
thanks @thiagokokada! works as well with the load block:
```toml
[[block]]
block = "load"
interval = 1
format = " $icon$1m.eng(w:3) "
```
