### ISSUE TITLE
add `prev_timezone` action to `time` block

### ISSUE THREAD

**Issue by tetraxile** [greshake/i3status-rust#1833]
i have several timezones in the `time` block in my config, and i've been using the `next_timezone` action implemented in #1759, but i'd like to be able to scroll through the timezones rather than needing to click through them all to go back by one.

maybe this could even be the default behavior, but ideally i'd have the config look like this:
```toml
# block = "time" ...
[[block.click]]
button = "up"
action = "prev_timezone"
[[block.click]]
button = "down"
action = "next_timezone"
```
