### ISSUE TITLE
Calibright config error on i3status-rust 0.30.7 (commit cb994547)

### ISSUE THREAD

**Issue by AkechiShiro** [greshake/i3status-rust#1870]
Hi, I've recently built the latest version from git i3status-rs 0.30.7 (commit cb994547 2023-04-15) and my backlight block shows `calibright config error`
![image](https://user-images.githubusercontent.com/14914796/232868496-ffc25930-54e6-4990-ae06-8b2a20355e03.png)

Backlight block configuration:
```toml
[[block]]
block = "backlight"
device = "amdgpu_bl0"
invert_icons = false
```

Is anyone else able to reproduce this issue ?
