### ISSUE TITLE
Path expansion with glob for maildir inboxes

### ISSUE THREAD

**Issue by lahwaacz** [greshake/i3status-rust#1874]
I have about 20 inboxes in which a new mail can arrive. Can you add glob support so that I can have something like
```toml
[[block]]
block = "maildir"
inboxes = ["~/Maildir/account1/*"]
```
instead of having to list all individual boxes?
