### ISSUE TITLE
Battery report: Failed to get capacity

### ISSUE THREAD

**Issue by deimosfr** [greshake/i3status-rust#1890]
Hi,

I randomly encounter issues with two Logitech devices (mouse and keyboard). The battery report will work for several hours, then stop working. It never gets back to work until I reload i3. Here is the config I'm using:

```toml
# keyboard battery
[[block]]
block = "battery"
model = "MX Keys Wireless Keyboard"
format = "$icon $percentage"
full_format = " $percentage "
missing_format = ""
driver = "sysfs"
merge_with_next = true
interval = 300

# mouse battery
[[block]]
block = "battery"
model = "Wireless Mouse MX Master 3"
format = "$icon $percentage"
full_format = "󰍽 $percentage "
missing_format = ""
driver = "sysfs"
interval = 300
merge_with_next = true
```

![image](https://user-images.githubusercontent.com/2962805/235716094-6c546f55-d030-4553-929e-e4840f4a8a5f.png)

Is there something wrong with my configuration?

Thanks
