### ISSUE TITLE
Change the default `error_fullscreen_format`

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1898]
Some errors are way too long to fit into the width of the status bar. Perhaps a better default for `error_fullscreen_format` would be something like

```toml
[error_fullscreen_format]
full = " $full_error_message "
short = " $full_error_message.str(w:170, rot_interval:0.2) "
```
