### ISSUE TITLE
Invalid `button` in a click handler does not result in an error

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1918]
```toml
[[block.click]]
button = "nonexisting"
```

does not error, it it probably should.
