### ISSUE TITLE
Questions regarding resource usage optimizations

### ISSUE THREAD

**Issue by Delgan** [greshake/i3status-rust#1921]
Hi!

I was wondering about possible optimizations made or not by `i3status-rust`, to be as "resource-friendly" as possible.

Let's take this example configuration:

```toml
[theme]
theme = "solarized-dark"

[icons]
icons = "awesome4"

[[block]]
block = "time"
format = " ^icon_calendar $timestamp.datetime(f:'%F') "
interval = 5

[[block]]
block = "time"
format = " ^icon_time $timestamp.datetime(f:'%R') "
interval = 5
```

1. I can see that even if both blocks have the same `interval` value, `i3status-rs` emit two messages every 5 seconds. I would expect a single message to be sent every 5 seconds. I assume this is because calls are `async`, correct?
2. I observe that even if the output does not change, `i3status-rs` still sends a message. However, there will be nothing to re-render on the bar since nothing has changed. Why send a message anyway?
3. In the example, I have two blocks that relies on the same `time` resource. I imagine that the time will be requested twice, whereas once would have been sufficient, to then update the `format` only. Is it possible to derive one block from another to reduce redundant calls (while keeping the blocks separate, and assigning them different click events)?
4. There exists [`yambar`](https://codeberg.org/dnkl/yambar/src/branch/master) with goals similar to `i3status-rust` regarding resource-friendliness. It does some clever tricks for optimization reasons, such as [updating the clock only once per minute](https://codeberg.org/dnkl/yambar/src/commit/d236b9c1b929262e2ae3215425aa698f2eb5b3e6/modules/clock.c#L106-L114) while preserving accuracy.  Is this something that has been considered by `i3status-rust`?

Thanks.
