### ISSUE TITLE
transition into the blocks looks ugly

### ISSUE THREAD

**Issue by qrockz** [greshake/i3status-rust#1959]
![2023-oct-26--23-04-22_maim](https://github.com/greshake/i3status-rust/assets/56853194/f8605c91-5bda-43da-8212-bfe2952c7cad)

As you can see the triangle does not really fit the height of the block.  Howto solve this?
Even in the theme pictures provided by this repo you can also see a not so smooth transition from the **triangle** to the **blocks**. It looks unclean and not eyecandy.
[theme](https://github.com/greshake/i3status-rust/blob/v0.32.0/img/themes/gruvbox-light.png?raw=true)

**Comment by bim9262** [comment]
Check out the discussion here #1865.

I personally use:

```toml
[theme]
theme = "solarized-dark"

[theme.overrides]
separator = "<span size='12pt'></span>"
```
