### ISSUE TITLE
packages: add `brew` and `snap` backends

### ISSUE THREAD

**Issue by zheltikov** [greshake/i3status-rust#1964]
Hello!

For systems where the `snap` and `brew` package managers are installed (apart from `apt`) it would be useful to have blocks that show available updates for those package managers too. The preferred configuration for these blocks would be practically identical the config of the `apt` block, excluding the block name obviously.

To list available updates for `snap`, you can run: `$ snap refresh --list`
To list available updates for `brew`, you can run: `$ brew outdated`

Some preferred icons for each block would be:
- `snap`: "🐦" or "📦"
- `brew`: "🍺"

Thanks!

**Comment by MaxVerevkin** [comment]
I wonder if it would be a good idea to merge all package blocks (apt, pacman, ...) into one since they all have a very similar config and structure.

**Comment by zheltikov** [comment]
Probably we should create a new "updates" or "packages" block, with the ability to configure "backends" for it.
Configuration would be like so:
```toml
[[block]]
block = "updates"
format = " $icon $count.eng(w:1) "
format_up_to_date = ""
package_manager_backends = ["apt", "pacman", "brew", "snap"]
```
@MaxVerevkin, thoughts on this approach?
