### ISSUE TITLE
My wireless adapter is being detected as an ethernet connection by the net block since the last update

### ISSUE THREAD

**Issue by gnsfujiwara** [greshake/i3status-rust#1969]
The current block config is:

```toml
[[block]]
block = "net"
format = " $icon {$ssid ($signal_strength)|Wired connection} "
inactive_format = " $icon No connection "
```
