### ISSUE TITLE
amd_gpu: improve the error when a device does not exist

### ISSUE THREAD

**Issue by heitorPB** [greshake/i3status-rust#2034]
I updated my system and got the 0.33.0 i3status-rs, but I saw a red block on my status bar saying `Failed to read gpu_busy_percent`.

My config for this block is:
```toml
[[block]]
block = "amd_gpu"
device = "card0"
format_alt = "$icon $vram_used.eng(w:2,u:B,p:Mi)/$vram_total.eng(w:1,u:B,p:Gi)"
interval = 2
```

If I manually run `i3status-rs`, the JSON for this block is this:
```json
{
  "full_text": "Failed to read gpu_busy_percent ",
  "color": "#002B36FF",
  "background": "#DC322FFF",
  "name": "4",
  "instance": "4:",
  "separator": false,
  "separator_block_width": 0,
  "markup": "pango"
}
```
