### ISSUE TITLE
`sound`: Make the warning status when muted configurable

### ISSUE THREAD

**Issue by snicket2100** [greshake/i3status-rust#2052]
Currently the behaviour to show the `sound` block in warning style whenever audio is muted is hardcoded in the block code.

I can easily imagine that I could want to make it configurable, for example to have it in warning style whenever audio is _not muted_, convenient for using a laptop in public places for example.

**Comment by MaxVerevkin** [comment]
> for example to have it in warning style whenever audio is _not muted_, convenient for using a laptop in public places for example.

You can do that now:

```toml
[block.theme_overrides]
idle_fg = { link = "warning_fg" }
idle_bg = { link = "warning_bg" }
warning_fg = { link = "idle_fg" }
warning_bg = { link = "idle_bg" }
```
