### ISSUE TITLE
Toggle Block:  opt-out of waiting for command_on execution end

### ISSUE THREAD

**Issue by tkapias** [greshake/i3status-rust#2095]
## Issue

Since issue #167 and PR #648, Toggle block operations are nullified if the result of command_on/command_off is not positive.

I understand that in most cases it's a better setting and probably that an error from command_on/command_off would always be a break-point. But, I have a case where I want the toggle to be effective even if command_on is still running.

## Context

I wrote [bemenu-desktop-menu](https://github.com/tkapias/bemenu-desktop-menu), a wrapper for bemenu to get a desktop launcher. Bemenu is a keyboard tool, there is no feature to close it with the mouse. So I want it in i3status-rust as a toggle button to be able to close it with the mouse if I want.

My wrapper is a bash script that runs bemenu, grabs the keyboard and waits for the user selection. It closes only when selecting a desktop entry or if the user cancels it.

So I wanted to use pgrep/pkill in the toggle block:

```toml
[[block]]
block = "toggle"
format = " MENU  "
command_state = "pgrep --full 'bemenu.*--prompt 󰣆 Desktop Menu'"
command_on = "bemenu-desktop-menu"
command_off = "pkill --signal SIGTERM --full 'bemenu.*--prompt 󰣆 Desktop Menu'"
state_on = "good"
state_off = "idle"
interval = 2
```

But, it does not work because while `bemenu-desktop-menu` is running, the toggle block will wait for command_on to finish, and so the state does not change while it's open and a second click on the button will open a second instance of the menu.

## Suggestions

Add a new option to indicate that command_on is not gonna finish before the toggle. It could be like "wait_command_on = false" maybe.
