### ISSUE TITLE
Regression: keyboard_layout block fails to get current layout from sway

### ISSUE THREAD

**Issue by heitorPB** [greshake/i3status-rust#2132]
I updated my system yesterday and i3status-rust (0.33.2) now fails to get the keyboard layout from sway. I changed no config whatsoever.

This was previously working:
```toml
[[block]]
block = "keyboard_layout"
driver = "sway"
format = "$layout"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"

[block.mappings]
"English (US, alt. intl.)" = "EN"
"Portuguese (Brazil, IBM/Lenovo ThinkPad)" = "PT"
```

But now I get this output:
```console
$ i3status-rs ./config-main.toml
{"version": 1, "click_events": true}
[
[{"full_text":"|","color":"#A9A9A9FF","background":"#000000FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":" ","color":"#DC322FFF","background":"#000000FF","name":"0","instance":"0:","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"failed to get current input ","color":"#DC322FFF","background":"#000000FF","name":"0","instance":"0:","separator":false,"separator_block_width":0,"markup":"pango"}],
^C
```

Not sure how to troubleshoot this further, any ideas?
