### ISSUE TITLE
taskwarrior block default config can cause high CPU usage

### ISSUE THREAD

**Issue by t4k1t** [greshake/i3status-rust#2165]
Hey, I noticed that the `swaybar` process was using 0.4% CPU usage of my AMD Ryzen 7 PRO 6850U. The reason seems to be that with the default config, `inotify` wakes up the block all the time. When I checked the `~/.task` dir, I noticed 3 files:
- taskchampion.sqlite3
- taskchampion.sqlite3-wal
- taskchampion.sqlite3-shm

and their timestamps got updated all the time, which in turn caused `inotify` within the block to trigger (which again updates the timestamps and so forth).

Example config to reproduce issue
```toml
[[block]]
block = "taskwarrior"
format = " $icon $count ($filter_name) "
warning_threshold = 1
[[block.filters]]
name = "today"
filter = "+PENDING +OVERDUE or +DUETODAY"
[[block.filters]]
name = "all"
filter = "+PENDING"
```

I didn't check if this also happens without filters, but I think filters are a pretty common use case.

Explicitly setting the `data_location` to the sqlite file in the config fixes the issue (in this case the `-wal` and `-shm` files aren't even created):
```toml
[[block]]
data_location = "/home/tsk/.task/taskchampion.sqlite3"
```

So unless there is a specific reason to watch the entire directory, it might be an easy fix to change the default location to `~/.task/taskchampion.sqlite3`:
```patch
diff --git a/src/blocks/taskwarrior.rs b/src/blocks/taskwarrior.rs
index 5370e0a8d..dc3e18183 100644
--- a/src/blocks/taskwarrior.rs
+++ b/src/blocks/taskwarrior.rs
@@ -79,7 +79,7 @@ impl Default for Config {
             format: default(),
             format_singular: default(),
             format_everything_done: default(),
-            data_location: ShellString::new("~/.task"),
+            data_location: ShellString::new("~/.task/taskchampion.sqlite3"),
         }
     }
 }
```

For me `swaybar` CPU usage went down to ~0.1% after this patch/config change.
