### ISSUE TITLE
Show also IPv6

### ISSUE THREAD

**Issue by svenstaro** [greshake/i3status-rust#237]
Currently, only the IPv4 is shown if available. I would also like to see the IPv6 if the interface has one.

**Comment by atheriel** [comment]
This sounds like a nice addition. Would you want it to show both? We could have a new configuration option along the lines of the following:

```toml
[[block]]
block = "net"
show_ip = "ipv4" # Default
show_ip = "ipv6" 
show_ip = "both"
```

**Comment by svenstaro** [comment]
I would have imagine it more like
```toml
[[block]]
block = "net"
show_ipv4 = "true" # Default
show_ipv6 = "true" 
```

And yes, I'd like it to show both.
