### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by SicariusNoctis** [greshake/i3status-rust#239]
Is it possible to support `left, center, right` align modes like polybar?

[![](https://i.imgur.com/jj71GnR.png)](https://imgur.com/a/JK2Pc6m)

Particularly useful for anchoring window titles to left or center.

Proposed implementation with `[[group]]` separators:

```toml

[[group]]
align = "left"

[[block]]
name = "music"


[[group]]
align = "center"

[[block]]
name = "title"


[[group]]
align = "right"

[[block]]
# All other blocks...
```
