### ISSUE TITLE
Music block ramps up updates/sec over time, causing increasing CPU usage

### ISSUE THREAD

**Issue by sebastianst** [greshake/i3status-rust#290]
I use the most recent git version of i3status-rust. On my 8 threaded desktop, the `i3bar` process shows an ever increasing CPU usage.
```bash
# ps -ewwo %cpu,args --sort=-%cpu | head      
%CPU COMMAND
 8.0 i3bar --bar_id=bar-0 --socket=/run/user/$UID/i3/ipc-socket.14743
 4.6 /usr/lib/firefox/firefox
 3.1 /usr/lib/firefox/firefox ...
 2.5 /usr/lib/Xorg -nolisten tcp :0 ...
 2.4 /usr/share/spotify/spotify
 1.5 /usr/lib/thunderbird/thunderbird
 1.4 i3status-rs /home/$USER/.config/i3/status.toml
```
So since start the average was 8%, but at the time of writing, in `htop` it hovers around 17%.
Restarting i3 in-place, which restarts `i3bar`, brings its CPU usage back down to below 1%.
Everything else works just fine btw.

My config
```toml
theme = "solarized-dark"
[icons]
name = "awesome"
[icons.overrides]
cpu = "⚡"
music = ""

[[block]]
block = "music"
player = "spotify"
max_width = 36
buttons = ["play", "next"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
name = "networkmanager"

[[block]]
block = "memory"
format_mem = "{Mug}GB({Mup}%)"
format_swap = "{SUg}GB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
info = 15
warning = 50
interval = 1
frequency = true

[[block]]
block = "load"
format = "{1m} {5m}"
interval = 3

[[block]]
block = "weather"
format = "{weather} {temp}° {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "<secret>", city_id = "<my_city_id>", units = "metric" }

[[block]]
block = "time"
format = "%a %d/%m %T"
timezone = "Europe/Berlin"
interval = 60

[[block]]
block = "sound"
step_width = 3
on_click = "pavucontrol"

[[block]]
block = "custom"
command = "/home/$USER/bin/xkb-layout-icon.sh"
interval = 1
on_click = "xkb-switch -n"

[[block]]
block = "pacman"
interval = 3600

```
Custom block script `/home/$USER/bin/xkb-layout-icon.sh`:
```
#!/bin/bash
case $(xkb-switch) in
us)
  printf '🇺🇳' ;;
de)
  printf '🍺' ;;
esac
```

My guess: For some reason, the data that i3status-rs passes to i3bar is getting bigger and bigger, so it has to process more and more data. But that's just a wild guess.
