### ISSUE TITLE
Battery time calculation is off

### ISSUE THREAD

**Issue by mmerfort** [greshake/i3status-rust#305]
Today I noticed that i3status-rust is reporting an incorrect value for the remaining charge time:
![img-2018-11-26-094037](https://user-images.githubusercontent.com/395822/49002559-3ac5dc00-f160-11e8-97ab-55dbe966a8bf.png)
Output from commandline:
```
[{"background":null,"color":"#ffc107","full_text":"","markup":"pango","separator":false,"separator_block_width":0},{"background":"#ffc107","color":"#000000","full_text":" / 18.72 GB ","separator":false,"separator_block_width":0},{"background":"#ffc107","color":"#535353FF","full_text":"","markup":"pango","separator":false,"separator_block_width":0},{"background":"#535353FF","color":"#FFFFFFFF","full_text":" /home 109.47 GB ","separator":false,"separator_block_width":0},{"background":"#535353FF","color":"#424242","full_text":"","markup":"pango","separator":false,"separator_block_width":0},{"background":"#424242","color":"#ffffff","full_text":"  40.13% ","name":"memory","separator":false,"separator_block_width":0},{"background":"#424242","color":"#535353FF","full_text":"","markup":"pango","separator":false,"separator_block_width":0},{"background":"#535353FF","color":"#FFFFFFFF","full_text":"  08%
","separator":false,"separator_block_width":0},{"background":"#535353FF","color":"#2196f3","full_text":"","markup":"pango","separator":false,"separator_block_width":0},{"background":"#2196f3","color":"#ffffff","full_text":"  1.70 ","separator":false,"separator_block_width":0},{"background":"#2196f3","color":"#9CD45BFF","full_text":"","markup":"pango","separator":false,"separator_block_width":0},{"background":"#9CD45BFF","color":"#111111FF","full_text":"  100% 307445734561825860:02 ","separator":false,"separator_block_width":0},{"background":"#9CD45BFF","color":"#8bc34a","full_text":"","markup":"pango","separator":false,"separator_block_width":0},{"background":"#8bc34a","color":"#000000","full_text":"  94% 0:00 ","separator":false,"separator_block_width":0},{"background":"#8bc34a","color":"#535353FF","full_text":"","markup":"pango","separator":false,"separator_block_width":0},{"background":"#535353FF","color":"#FFFFFFFF","full_text":"  2018-11-26 09:44:25 ","name":"1c4e1fb67c9940b284713c66060a5f73","separator":false,"separator_block_width":0}],
```

Output from upower:
```
$ upower -i /org/freedesktop/UPower/devices/battery_BAT0  
  native-path:          BAT0
  vendor:               LGC
  model:                45N1113
  serial:               2080
  power supply:         yes
  updated:              Mon 26 Nov 2018 09:43:51 CET (115 seconds ago)            
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               charging
    warning-level:       none
    energy:              22.38 Wh
    energy-empty:        0 Wh
    energy-full:         23.89 Wh
    energy-full-design:  23.48 Wh
    energy-rate:         2.841 W
    voltage:             12.684 V
    time to full:        31.9 minutes
    percentage:          100%
    capacity:            92.632%
    technology:          lithium-ion
    icon-name:          'battery-full-charging-symbolic'  
```

My config
```toml
theme = "slick"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
device = 'BAT1'
# [[block]]
# block = "sound"

[[block]]
block = "time"
interval = 5
format = "%F %X"
```

I'm using version 0.9.0.r567.ga72c86c-1 from the AUR on Arch Linux.
