### ISSUE TITLE
Weather: Malformed JSON but curl succeeds

### ISSUE THREAD

**Issue by yangmillstheory** [greshake/i3status-rust#321]
```
┌─ caladan ~/Downloads
└─ curl -m 3 http://api.openweathermap.org/data/2.5/weather\?id\=5400075\&appid\=MY_API_KEY\&units\=imperial
{"coord":{"lon":-122.04,"lat":37.37},"weather":[{"id":721,"main":"Haze","description":"haze","icon":"50d"},{"id":701,"main":"Mist","description":"mist","icon":"50d"}],"base":"stations","main":{"temp":58.17,"pressure":1029,"humidity":74,"temp_min":55.4,"temp_max":60.8},"visibility":16093,"wind":{"speed":3.27,"deg":110.501},"clouds":{"all":90},"dt":1547921700,"sys":{"type":1,"id":5122,"message":0.006,"country":"US","sunrise":1547911169,"sunset":1547947146},"id":5400075,"name":"Sunnyvale","cod":200}% 
```

Yet the error message I see in the bar is

>Error in block 'weather': Malformed JSON.

**Comment by yangmillstheory** [comment]
Config. is exactly the same as in the docs, but with my API key inject (same as that which I use in `curl`).

```
[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "XXX", city_id = "5398563", units = "metric" }
```

**Comment by atheriel** [comment]
Do you always see this error or only sometimes? Also, I note that there is a trailing `%` in the JSON output -- is that just a typo, or is it always there for you? If so, that would account for the "malformed JSON" error.

**Comment by Autotonic** [comment]
I am getting this same error with the block.
```toml
[[block]]
block = "weather"
format = "{temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "API_KEY", city_id ="CITY_ID", units = "imperial" }
```
Only happens sometimes.
@atheriel the trailing `%` is from zsh
