### ISSUE TITLE
Custom block with `cycle` that is only run once?

### ISSUE THREAD

**Issue by sersorrel** [greshake/i3status-rust#325]
I have a block to turn on and off my compositor, using a couple of scripts I wrote:

```toml
[[block]]
block = "custom"
cycle = ["coff --icon", "con --icon"]
```

but i3status-rust likes to run the command again every `interval` seconds, which means I end up with debug messages telling me that the compositor is already enabled in my status bar.

Is there a way to make the command only be run once, and never again (until it's clicked and the next command is run), except for setting `interval` to 2 billion?
