### ISSUE TITLE
Battery module only shows icon 

### ISSUE THREAD

**Issue by wulftone** [greshake/i3status-rust#326]
I'm on Arch on `i3status-rust-git 0.9.0.r607.g550b600-1`

I have the battery module installed like so:
```toml
[[block]]
block = "battery"
interval = 10
show = "percentage"
```

and the output is like this:
```json
  {
    "background": "#8bc34a",
    "color": "#000000",
    "full_text": "   ",
    "separator": false,
    "separator_block_width": 0
  },
``` 
That is a battery symbol, which works fine, but there is no other text.  Not sure what I'm missing.... ?
