### ISSUE TITLE
Allow custom blocks to (configurably) indicate state via exit code

### ISSUE THREAD

**Issue by OddBloke** [greshake/i3status-rust#331]
I have a systemd job that from time-to-time fails; I've written a custom block which calls `systemctl` to find out what the status of the unit is. `systemctl` will return 0 if the unit is running as expected, or 1-4 if it isn't (with each return code meaning a different failure state).

I would like to extend the custom plugin to have configuration along the lines of:

```toml
[[block]]
block = "custom"
command = "systemctl ..."
good_exitcode = 0
warn_exitcode = 3
critical_exitcode = 4
```

When my command exits with those specific exitcodes, I would then like the custom plugin to set the state appropriately.

(This proposal is related to #165, but I believe it is complimentary. Integrating at the exit code level works with a broad range of existing programs without JSON-producing wrappers, but isn't as rich an interface for programs that are looking to integrate specifically with i3status-rust.)
