### ISSUE TITLE
Add CI verification step

### ISSUE THREAD

**Issue by pitkley** [greshake/i3status-rust#40]
PRs (and `master` for that matter) are currently not checked for anything, potentially causing [`master` not to build](https://github.com/greshake/i3status-rust/issues/30#issuecomment-304526359).

I propose to add a simple CI configuration, using one of the numerous free CI solutions like [Travis CI](https://travis-ci.org) or [Circle CI](https://circleci.com/).

-----

Following is a very simple Travis configuration (`.travis.yml`) which at least checks if a commit builds successfully:

```yaml
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build -v
  - cargo test
```

(I have added `cargo test` although there aren't any tests yet. This will take the burden of remembering to add a test-run to the CI configuration once tests might be added.)
