### ISSUE TITLE
TOML format not honored

### ISSUE THREAD

**Issue by HaoZeke** [greshake/i3status-rust#487]
As per the [TOML docs](https://github.com/toml-lang/toml), the following:

```toml
service = { name="openweathermap", city_id="1267995", units="metric" }
```

Should be equivalent to:

```toml
[service] # Table format instead of the inline table {} format
name = "openweathermap"
city_id = "1267995" # Kanpur
# city_id = "3413829", # Reykjavik
units = "metric"
```

However, the table format is not accepted, with the error being:

```
Configuration error: Failed to deserialize block config.. 
Cause: missing field `service`
```

Any idea what might be causing this?

**Comment by atheriel** [comment]
I believe you are misreading the specification, particularly the [**Array of Tables**](https://github.com/toml-lang/toml#array-of-tables) section. The following works as expected:
```toml
[[block]]
block = "weather"

[block.service]
name = "openweathermap"
city_id = "1267995" # Kanpur
units = "metric"
```
For reference, we don't implement TOML parsing ourselves -- we use the standard `toml` crate, which I believe is very careful about spec compliance.
