### ISSUE TITLE
net block: extraneous spaces around IP address

### ISSUE THREAD

**Issue by majewsky** [greshake/i3status-rust#498]
I have two `net` blocks for my physical interfaces, and I've set them up so that it only shows the IP address:

```toml
[[block]]
block = "net"
device = "enp2s0" # or "wlp4s0" for wireless
ip = true
hide_inactive = true

ssid = false
signal_strength = false
bitrate = false
speed_up = false
speed_down = false
graph_up = false
graph_down = false
```

The layout looks fine for a disconnected interface, but when an IP has shown, it has unpleasant extra spaces around it:

![foo](https://user-images.githubusercontent.com/24696/71671091-f1d05600-2d69-11ea-99fb-85cb5e6e83af.png)

i3status-rust is version 0.12, the compositor is Sway 1.2 with the following bar config:

```
bar {
    position top
    font pango:Hack 12
    height 28
    status_command i3status-rs /path/to/i3status-rust.toml
    tray_padding 0

    colors {
        ...
    }
}
```

**Comment by ammgws** [comment]
Do the same spaces appear for the non-wireless device block as well?

**Comment by majewsky** [comment]
If it's connected, yes. Also, the WiFi block has the correct spacing when not connected, like the ethernet block in the screenshot above.

**Comment by ammgws** [comment]
What about when you set ip to false and SSID to true?

**Comment by ammgws** [comment]
OK so I just submitted #505 and #507 which should improve the situation.

Unfortunately you will still end up with two spaces between each part of the `net` block apart from the end one, because each part (ip, SSID, etc) has its own ButtonWidget, and ButtonWidget pads its text with spaces before (if no icon) and after. So if two ButtonWidgets are displayed side by side you end up with two spaces between them...

**Comment by amitlevy21** [comment]
![image](https://user-images.githubusercontent.com/28672915/90247252-e46e6480-de3e-11ea-9753-c41750487fb0.png)
![image](https://user-images.githubusercontent.com/28672915/90247447-4202b100-de3f-11ea-90b3-1dc3caedbf50.png)

@ammgws  can anything be done to remove the spaces marked in the red boxes?

**Comment by ammgws** [comment]
Can you share your config for the net block?

**Comment by amitlevy21** [comment]
Sure! 
```toml
[theme]
name = "solarized-dark"

[theme.overrides]
idle_fg = "#FFFFFF"
alternating_tint_bg = "#0088CC"

[icons]
name = "awesome5"

[icons.overrides]
net_wired = ""
net_wireless = ""

[[block]]
block = "net"
device = "wlp0s26u1u5"
speed_up = true
speed_down = true
interval = 5

```
