### ISSUE TITLE
Panick if sound is the only module

### ISSUE THREAD

**Issue by diegodorado** [greshake/i3status-rust#581]
If `config.toml` si only this,
```toml
[[block]]
block = "sound"
```
 I get this error: 
`thread 'main' panicked at 'overflow when adding duration to instant', src/libcore/option.rs:1188:5`

Error goes away as soon as I add another module.
```toml
[[block]]
block = "cpu"
[[block]]
block = "sound"
```
