### ISSUE TITLE
Battery Block background color

### ISSUE THREAD

**Issue by mismosmi** [greshake/i3status-rust#629]
Hi,
sorry to bother.

I hope this is just a config issue but I can't seem to figure out what's wrong on my own so maybe you can help me.

My problem is that the battery block does not seem to obey my set background colors:

![Screenshot from 2020-05-02 20-19-38](https://user-images.githubusercontent.com/26325283/80872499-9b8d0880-8cb2-11ea-9dcd-5db719755a41.png)

Config is
```toml
icons = "awesome"

[[block]]
block = "net"
device = "enp0s25"
ip = true
speed_down = true
interval = 10

[[block]]
block = "net"
device = "wlp3s0"
ip = true
speed_up = true
speed_down = true
interval = 10

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "load"
format = "{5m}"
interval = 20

[[block]]
block = "pacman"
interval = 3600

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Google Dark by Seth Wright (http://sethawright.com)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#c5c8c6"
info_bg = "#000000"
info_fg = "#3971ED"
good_bg = "#000000"
good_fg = "#198844"
warning_bg = "#000000"
warning_fg = "#FBA922"
critical_bg = "#000000"
critical_fg = "#CC342B"
```

Thanks in advance.
