### ISSUE TITLE
theme override fails

### ISSUE THREAD

**Issue by andersfylling** [greshake/i3status-rust#731]
Hi, after reading themes.md I added the following to my config file:

[theme]
name = "slick"
[theme.overrides]
good_bg = "#82b3db"

The goal was to adjust the colour of the spotify block. I'm more experimenting right now as it isn't imminently obvious to me how this is done.

However, this causes a failure that complains about multiple theme fields. "duplicate field `theme` at line ...".

Is there something I'm misunderstanding here?

Edit:
version: v0.13.0
installed via AUR, pkg: i3status-rust-git

**Comment by ammgws** [comment]
What version are you using? 

I just tried the config below with git master and didn't get any errors

```toml
[theme]
name = "slick"
[theme.overrides]
good_bg = "#82b3db"

[[block]]
block = "uptime"
```

**Comment by andersfylling** [comment]
version: v0.13.0
installed via AUR, pkg: i3status-rust-gitversion: v0.13.0

**Comment by andersfylling** [comment]
I now remove the AUR dep and built it manually. I still have the same issue. 

i3 config:
```markdown
bar {
    output DP-4
    #i3bar_command i3bar --transparency
    font pango:DejaVu Sans Mono, FontAwesome 12
    position top
    status_command i3status-rs ~/.config/i3/status.toml
    colors {
        separator #666666
        background #222222
        statusline #dddddd
        focused_workspace #0088CC #0088CC #ffffff
        active_workspace #333333 #333333 #ffffff
        inactive_workspace #333333 #333333 #888888
        urgent_workspace #2f343a #900000 #ffffff
    }
    height 25
}
```

status.toml
```toml
theme = "slick"
icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
good_bg = "#82b3db"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
```
