### ISSUE TITLE
Focused window block stuck on Alacritty

### ISSUE THREAD

**Issue by amitlevy21** [greshake/i3status-rust#786]
Hey,

The block focused window keeps showing the same window name regardless which window is focused:
![image](https://user-images.githubusercontent.com/28672915/88819459-afb8a700-d1c8-11ea-81e0-aaeffefa6bff.png)

Here is the config I'm using:
```toml
[theme]
name = "solarized-dark"

[theme.overrides]
idle_fg = "#FFFFFF"
alternating_tint_bg = "#0088CC"

[icons]
name = "awesome5"

[icons.overrides]
net_wired = ""
net_wireless = ""

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "disk_space"
path = "/home"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 5.0
alert = 2.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "wlp0s26u1u5"
speed_up = true
speed_down = true
interval = 5

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
```

It reproduces with a minimal config:
```toml
[theme]
name = "solarized-dark"

[icons]
name = "awesome5"

[[block]]
block = "focused_window"
max_width = 21
```

The issue happens only with Alacritty terminal and only when the following setting is set in alacritty.yml:
```yml
dynamic_title: false
```
Which does not change the window name of Alacritty when running a command.
For example, it doesn't change the window name from 'Alacritty' to yay when running the yay command from the terminal.

I don't know how alacritty achieves this feature.

Here is the output of xprop and clicking the terminal window:
```
WM_HINTS(WM_HINTS):
_NET_WM_DESKTOP(CARDINAL) = 1
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
_NET_WM_ICON(CARDINAL) =
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified size: 800 by 600
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
WM_CLIENT_MACHINE(STRING) = "amit-pc"
_NET_WM_PID(CARDINAL) = 27638
WM_CLASS(STRING) = "Alacritty", "Alacritty"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_NAME(UTF8_STRING) = "Alacritty"
WM_NAME(STRING) = "Alacritty"
```

Here is, for example, xprop + google's chrome which shows a different `WM_CLASS(STRING)` value
```
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 20971522, 20971523
WM_WINDOW_ROLE(STRING) = "browser"
WM_CLASS(STRING) = "google-chrome", "Google-chrome"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 3996
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "amit-pc"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```

Am I missing something here?

Thank you for your time
