### ISSUE TITLE
Custom theme isn't working

### ISSUE THREAD

**Issue by PopeRigby** [greshake/i3status-rust#868]
The default theme keeps getting loaded even though I've set a custom theme. Am I doing something wrong? Here's my config:

`~/.config/i3status-rust/config.toml`
```
theme = "dracula.toml"
icons = "awesome"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
```

`~/.config/i3status-rust/themes/dracula.toml`
```
idle_bg = "#44475a"
idle_fg = "#f8f8f2"
info_bg = "#44475a"
info_fg = "#f8f8f2"
good_bg = "#50fa7b"
good_fg = "#f8f8f2"
warning_bg = "#f1fa8c"
warning_fg = "#f8f8f2"
critical_bg = "#ff5555"
critical_fg = "#f8f8f2"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "f8f8f2"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
```

**Comment by ammgws** [comment]
Did you copy and paste the wrong file in your post? Both have the same contents

**Comment by PopeRigby** [comment]
Whoops, seems I did. Sorry, fixed it.

**Comment by ammgws** [comment]
Change your config to:
```toml
[theme]
file = "dracula.toml"

[icons]
name = "awesome"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
```
