### ISSUE TITLE
Config error messages are bad

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#969]
When an unknown theme is provided:
```toml
[theme]
name = "nonexistent"

[[block]]
block = "time"
format = "%a %d/%m %R"
```
> {"version": 1, "click_events": true}
> [[{"background":"#000000","color":"#dc322f","full_text":" Configuration error: failed to parse TOML from file contents.\nCause: invalid type: map, expected a string for key `theme` at line 4 column 1 ","separator":false,"separator_block_width":0}]
> 
> Configuration error: failed to parse TOML from file contents.
> Cause: invalid type: map, expected a string for key `theme` at line 4 column 1

When a non-existing theme file is provided:
```toml
[theme]
file = "/this/does/not/exist.toml"

[[block]]
block = "time"
format = "%a %d/%m %R"
```

> {"version": 1, "click_events": true}
> [[{"background":"#000000","color":"#dc322f","full_text":" Configuration error: failed to parse TOML from file contents.\nCause: invalid type: map, expected a string for key `theme` at line 4 column 1 ","separator":false,"separator_block_width":0}]
> 
> Configuration error: failed to parse TOML from file contents.
> Cause: invalid type: map, expected a string for key `theme` at line 5 column 1

When a config section is provided twice:
```toml
[theme]
name = "slick"

[theme]
name = "plain"

[[block]]
block = "time"
format = "%a %d/%m %R"
```

> {"version": 1, "click_events": true}
> [[{"background":"#000000","color":"#dc322f","full_text":" Configuration error: failed to parse TOML from file contents.\nCause: invalid type: map, expected a string for key `theme` at line 7 column 1 ","separator":false,"separator_block_width":0}]
> 
> Configuration error: failed to parse TOML from file contents.
> Cause: invalid type: map, expected a string for key `theme` at line 7 column 1

When an unknown icon set is provided:
```toml
[icons]
name = "nonexistent"

[[block]]
block = "time"
format = "%a %d/%m %R"
```

> "version": 1, "click_events": true}
> [[{"background":"#000000","color":"#dc322f","full_text":" Configuration error: failed to parse TOML from file contents.\nCause: cannot find specified icons for key `icons` at line 4 column 1 ","separator":false,"separator_block_width":0}]
> 
> Configuration error: failed to parse TOML from file contents.
> Cause: cannot find specified icons for key `icons` at line 4 column 1

**Comment by ammgws** [comment]
Actually the icon one should be improved now due to d79d220af65810692bd9be24ac93e91d41d3b1c2:

> 
> {"version": 1, "click_events": true}
> [[{"background":"#000000","color":"#dc322f","full_text":" Configuration error: failed to parse TOML from file contents.\nCause: cannot find icon set called 'nonexistent' for key `icons` at line 4 column 1 ","separator":false,"separator_block_width":0}]
> 
> Configuration error: failed to parse TOML from file contents.
> Cause: cannot find icon set called 'nonexistent' for key `icons` at line 4 column 1

**Comment by ammgws** [comment]
Much better now with the recent work done by @MaxVerevkin 

When an unknown theme is provided:
```toml
[theme]
name = "nonexistent"

[[block]]
block = "time"
format = "%a %d/%m %R"
```
> Configuration error: failed to parse TOML from file contents.
> Cause: Theme "nonexistent" not found. for key `theme` at line 4 column 1

When a non-existing theme file is provided:
```toml
[theme]
file = "/this/does/not/exist.toml"

[[block]]
block = "time"
format = "%a %d/%m %R"
```
> Configuration error: failed to parse TOML from file contents.
> Cause: Failed to load theme from file /this/does/not/exist.toml. for key `theme` at line 4 column 1

When a config section is provided twice:
```toml
[theme]
name = "slick"

[theme]
name = "plain"

[[block]]
block = "time"
format = "%a %d/%m %R"
```
> Configuration error: failed to parse TOML from file contents.
> Cause: redefinition of table `theme` for key `theme` at line 4 column 1

When an unknown icon set is provided:
```toml
[icons]
name = "nonexistent"

[[block]]
block = "time"
format = "%a %d/%m %R"
```
> Configuration error: failed to parse TOML from file contents.
> Cause: cannot find icon set called 'nonexistent' for key `icons` at line 4 column 1
